auth:
  accKey: 455982646
  refreshToken: ******
  consumerKey: ******

api:
  tdAmeritradeApi:
    url: https://api.tdameritrade.com/v1
    authenticationEndpoint: /oauth2/token
    getAccountsEndpoint: /accounts/


