auth:
  accKey: 455982646
  refreshToken: XCufXqLqDErTwtdKjMvykBf5aQtgOqWiYJE69MedwmDJ7tfBgMi7k5cxZTo6Pod8/LyHKQRE/fmgZTt60fRAbhlGGni3PHiLVsW/+SZyTADjJL1PAQDoAaytKtBpFC+3OFwKoSnMnhI++uYA+kk5myQ1vvw6FvGCO4etEVDcDpwIcj3b7jHyoG+fUDeGAhuWtv6dmSxlgZn/TyVEDy/n7rtFYgoOzIpK/hSydEbq/LVymM0/Fhe5BPfWLMnzj6CepvlIfrgWZ2m1cgie2hLSN7/i7z6iJsZjptLkJi01A5KqJanwOl6tXBbBXbCXH5aaiNIc+12lEs7JAt9OQdQpee7BMFyCFv0lBHdNeRQFZOHHwarR2C7ZnwieW8gb5fZMuIjb2EGj/JQ+7FjRDkn4vhFOWh9XZ+ThWSLysPPGvCueykRGjScyORZkVZ9100MQuG4LYrgoVi/JHHvle2TUGmsTvDgRI3+7jtfa/IEYhEOOAvLmfsokxRUFjXGXmizCOFdaMRNHTTnk9boN1yxUu2HmFUnUmLX4N2jaPNZ0Kc7jNbLDPGI+IZ9K9MOLNs/uZwtBVDSGSdz4v/jfCBJaiIDQGVAaPlRcVgvk56T0BHUIajYLEJSNCvIsmCvdM7RQLsb3zhrzFxicePOW/GsWosNMAH9t0l5z22CLepxsKh7aiIiWGJRa6zXcKeSd5YvDALduBh9LuhXsRCbf42pVvdFUG2u+mNv60nClhpORWxOWrasqgDhlFdeusD0EAHlmeed57OBVU4Y1jah+t1MJLbEvJ9V1CHsEcHGG7IAMY36+SI75seOHNjvnVyTRuNiqk5S0xnrR4D+eDmsSy88BHqAIqwA7mO6xdVMaCCSdB9sgCpKIpr900DRthHKZOn0rJmf3ldG+Pek=212FD3x19z9sWBHDJACbC00B75E
  consumerKey: UCUDAHKS8XPA8LX7DM3GBZZQY1MICXZY

api:
  tdAmeritradeApi:
    url: https://api.tdameritrade.com/v1
    authenticationEndpoint: /oauth2/token
    getAccountsEndpoint: /accounts/


